name: Deploy API
on:
  push:
    tags:
      - "*" # Everything that doesnt include  '/' character

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER: ${{ vars.PRODUCTION_SERVER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRODUCTION_KEY }}
      SSH_USER: ${{ secrets.SSH_USER  || 'ubuntu' }}
      SSH_PORT: ${{ secrets.SSH_PORT || 22  }}
      FOLDER_NAME: ${{ vars.FOLDER_NAME || '/var/www/academy750-backend' }}

    steps:
      # - name: Only Main branch
      #   if: endsWith(github.ref, 'main') == false
      #   run: exit -1

      - name: 🚚 Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v2.2.4
        with:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ env.SERVER }}
          REMOTE_USER: ${{ env.SSH_USER }}
          REMOTE_PORT: ${{ env.SSH_PORT }}
          SOURCE: ""
          TARGET: "${{ env.FOLDER_NAME }}"
          ARGS: "-rltgoDzvO --delete"
          EXCLUDE: ".env, pm2.json, stubs/*, storage/framework/cache/*, storage/framework/session/*, storage/framework/views/*, storage/logs/*, storage/app/*, bootstrap/cache/*"

      - name: Installing the new version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ${{ env.FOLDER_NAME }}
            (php artisan down) || true
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan optimize
            php artisan migrate --force
            php artisan db:seed --class=PermissionSeeder --force
            php artisan up
            echo "🎉 Deployment finished!"

      - name: Updating Docs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ${{ env.FOLDER_NAME }}
            composer require --dev knuckleswtf/scribe
            php artisan route:clear
            APP_ENV=documentation php artisan scribe:generate
            sudo service supervisor restart
            echo "🎉 Docs ready!"
