name: Deploy API
on:
  push:
    branches:
      - main
    tags:
      - "*" # Everything that doesnt include  '/' character

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER: ${{ vars.STAGING_SERVER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      FOLDER_NAME: "production"

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v2.2.4
        with:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ env.SERVER }}
          REMOTE_USER: ubuntu
          REMOTE_PORT: 22
          SOURCE: ""
          TARGET: "/var/www/${{ env.FOLDER_NAME }}"
          ARGS: "-rltgoDzvO --delete"
          EXCLUDE: ".env, pm2.json"

      - name: Installing the new version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER }}
          username: ubuntu
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/${{ env.FOLDER_NAME }}
            (php artisan down) || true
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan optimize
            php artisan migrate --force
            php artisan up
            echo "🎉 Deployment finished!"
